<!doctype html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="icon" type="image/svg+xml" href="<?php _url('/assets/default/img/favicon.png'); ?>"> -->

    <?php include_asset('@default/css/styles.css'); ?>

    <title> <?php echo cfg('name') . ' | ' . esc($page_title ?? t("Sentence Describing This Site")); ?> </title>

  </head>

  <body>
